Repository jenkinsci/windows-slaves-plugin, pull requests merged in 2019-10, with the labels that each got.

#18 Use more common MIT license URL
  pom.xml
Labels: chore

#20 Enable Release Drafter in the repo
  .github/release-drafter.yml
Labels: chore, hacktoberfest

#19 Move Documentation from Wiki to GitHub
  CHANGELOG.adoc
  README.adoc
  docs/images/configuration.png
  docs/troubleshooting.adoc
  pom.xml
Labels: documentation, hacktoberfest

#21 Move plugin changelogs to GitHub releases, add badges
  README.adoc
Labels: documentation

#22 Update changelog.adoc to indicate that GitHub Releases is a new release notes source
  CHANGELOG.adoc
Labels: documentation, skip-changelog
