Repository jenkinsci/windows-slaves-plugin, pull requests merged in 2020-09, with the labels that each got.

#27 Replace esclave with agent in the French localization
  src/main/resources/hudson/os/windows/ManagedWindowsServiceLauncher/help-host_fr.html
  src/main/resources/hudson/os/windows/ManagedWindowsServiceLauncher/help_fr.properties
  src/main/resources/hudson/os/windows/Messages_fr.properties
Labels: bug

#26 Add firewall rule names to the troubleshooting guide
  docs/troubleshooting.adoc
Labels: documentation

#29 Update target configurations for the CI build
  Jenkinsfile
Labels: internal

#28 [JENKINS-63223] - Stop passing jenkins.exe.config is no longer available in the Core + Update Minimum Jenkins Core requirement to 2.249.1 + Use Bills of materials to specify core and plugin dependencies
  .gitignore
  Jenkinsfile
  pom.xml
  src/main/java/hudson/os/windows/ManagedWindowsServiceLauncher.java
Labels: bug, dependencies

#30 Replace the "slave" term in generated agent configuration files
  src/main/resources/hudson/os/windows/configsamples/jenkins-agent.xml
Labels: bug
